# Generated by Django 5.1.4 on 2025-02-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('idAudio', models.AutoField(primary_key=True, serialize=False)),
                ('audioBlob', models.BinaryField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('idVideo', models.AutoField(primary_key=True, serialize=False)),
                ('videoBlob', models.BinaryField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'videos',
                'managed': False,
            },
        ),
    ]
